#https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci
#https://github.com/harshjv/travis-ci-latex-pdf/blob/master/.travis.yml
#http://jankuester.com/using-travis-ci-latex-projects/
#https://mirocupak.com/continuous-integration-for-latex/
#https://github.com/thomastweets/cv-on-ghpages
#https://github.com/PHPirates/travis-ci-latex-pdf
#https://github.com/scottclowe/cv/blob/5763fbcaa8631b23f1bf729683a0fbc5b81d1e9b/.travis.yml
#https://github.com/scottkosty/install-tl-ubuntu
#https://github.com/Jery77/BA

sudo: required

language: generic

branches:
  only:
    - master

before_install:
  - chmod +x ./travis-install-tl.sh
  - sudo ./travis-install-tl.sh  
  - export PATH="/opt/texbin:$PATH"
  # - . /etc/environment # refresh PATH variable
  # latexmk has to be installed after install-tl-ubuntu to ensure that texlive is not taken from debian, but the latest one. In other words: addons->apt->packages cannot be used
  # - sudo apt-get install -y latexmk

script:
  - mkdir _build
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build latex/ManasTalukdar.tex
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build latex/ManasTalukdar_CV.tex
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build latex/ManasTalukdar_vNext.tex
  # - latexmk

# cache:
#   directories:
#     - /opt/texbin
#     - /usr/local/texlive

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: website
  on:
    branch: master
  target-branch: gh-pages