#https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci
#https://github.com/harshjv/travis-ci-latex-pdf/blob/master/.travis.yml
#http://jankuester.com/using-travis-ci-latex-projects/
#https://mirocupak.com/continuous-integration-for-latex/
#https://github.com/thomastweets/cv-on-ghpages
#https://github.com/PHPirates/travis-ci-latex-pdf
#https://github.com/scottclowe/cv/blob/5763fbcaa8631b23f1bf729683a0fbc5b81d1e9b/.travis.yml
#https://github.com/scottkosty/install-tl-ubuntu
#https://github.com/Jery77/BA

sudo: required

language: generic

branches:
  only:
    - master

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

install:
 - source ./texlive_install.sh

script:
  - mkdir _build
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build -include-directory latex latex/ManasTalukdar.tex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build -include-directory latex latex/ManasTalukdar_CV.tex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build -include-directory latex latex/ManasTalukdar_vNext.tex
  - cp ./_build/*.pdf ./website-legacy/resources/  

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: website-legacy
  on:
    branch: master
  target-branch: gh-pages