#https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci
#https://github.com/harshjv/travis-ci-latex-pdf/blob/master/.travis.yml
#http://jankuester.com/using-travis-ci-latex-projects/
#https://mirocupak.com/continuous-integration-for-latex/
#https://github.com/thomastweets/cv-on-ghpages
#https://github.com/PHPirates/travis-ci-latex-pdf

branches:
  only:
    - master

before_install:  
  - chmod +x ./scripts/build/texlive_install.sh
#   - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
  #texlive-base texlive-latex-base  texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra dvipng

install:
 - travis_wait 30 sudo ./scripts/build/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd ./latex/

script:
  - mkdir _build
  # Prefix command with travis_wait x so it times out after 3 mins, because when the LaTeX doesn't compile pdflatex just hangs instead of quitting.
  - travis_wait 3 pdflatex -output-directory _build ./latex/ManasTalukdar.tex
  # Compile twice to fix possible references
  - travis_wait 3 pdflatex -output-directory _build ./latex/ManasTalukdar.tex
  # - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build latex/ManasTalukdar.tex
  # - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build latex/ManasTalukdar_CV.tex
  # - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build latex/ManasTalukdar_vNext.tex

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: website
  on:
    branch: master
  target-branch: gh-pages