sudo: required

language: node_js
node_js:
  - "node"

branches:
  only:
    - main

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $TRAVIS_BUILD_DIR/website/node_modules

install:
 - source ./texlive_install.sh

script:
  - mkdir _build
  - cd latex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory ../_build ManasTalukdar.tex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory ../_build ManasTalukdar_cv.tex
  - cd ..
  - cd website
  - npm install  
  - cp ../_build/*.pdf ./public/resources/
  - CI=false npm run build # CI=false tells travis to not treat warnings as errors.

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: false
#   local-dir: website/build
#   on:
#     branch: main
#   target-branch: gh-pages