sudo: required

language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $TRAVIS_BUILD_DIR/website/node_modules

install:
 - source ./texlive_install.sh

script:
  - mkdir _build
  - cd latex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory ../_build ManasTalukdar.tex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory ../_build ManasTalukdar_CV.tex
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error -output-directory ../_build ManasTalukdar_vNext.tex
  - cd ..
  - cd website
  - npm install
  - CI=false npm run build
  - cp ../_build/*.pdf ./build/resources/

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: website/build
  on:
    branch: master
  target-branch: gh-pages